feature/CEMCA-2: Basic whatsapp component
sealabscr/cemca.co.cr pull request #3
Opened 2023-02-22 02:08 UTC by axelmairena-sealabs

# Description
Generated a basic whatsapp component. Would appreciate some feedback on the css. 
If you think anything can be changed, please let me know !!

# Issue number
https://sealabs.atlassian.net/browse/CEMCA-2

2023-02-23 02:57 UTC, jeanvega-sealabs commented
Hacer los cambios solicitados: 

- Incluir Shadow nuevo
   box-shadow: 0px 10px 50px rgba(0, 0, 0, 0.4);

- Aplicar logo de CEMCA

2023-02-23 02:58 UTC, jeanvega-sealabs requested changes
Revisar comentarios

2023-02-24 02:39 UTC, jeanvega-sealabs approved these changes

2023-02-24 02:40 UTC, samuelching-sealabs approved these changes

2023-02-24 02:54 UTC, merged